In [2]:
import numpy as np
import pandas as pd

 # Dictionaries Test

### In the following table, we want to find, for each client, the date when their total savings is over 1000 €.

In [3]:
ahorros_pd = \
    pd.DataFrame.from_dict(
        {'cliente': ['Cliente1', 'Cliente1', 'Cliente1', 'Cliente1', 'Cliente1', 'Cliente1',
                'Cliente2', 'Cliente2', 'Cliente2', 'Cliente2', 'Cliente2', 'Cliente2',
                'Cliente3', 'Cliente3', 'Cliente3', 'Cliente3', 'Cliente3', 'Cliente3',
                'Cliente4', 'Cliente4', 'Cliente4', 'Cliente4', 'Cliente4', 'Cliente4'],
        'fecha': [201901, 201902, 201903, 201904, 201905, 201906,
                201901, 201902, 201903, 201904, 201905, 201906,
                201901, 201902, 201903, 201904, 201905, 201906,
                201901, 201902, 201903, 201904, 201905, 201906],
        'ahorro': [150, 250, 0, 0, 0, 150,
                    250, 300, 320, 370, 250, 1200,
                    200, 100, 150, 0, 300, 300,
                    330, 290, 150, 180, 270, 350]})

In [4]:
ahorros_pd

     cliente   fecha  ahorro
0   Cliente1  201901     150
1   Cliente1  201902     250
2   Cliente1  201903       0
3   Cliente1  201904       0
4   Cliente1  201905       0
5   Cliente1  201906     150
6   Cliente2  201901     250
7   Cliente2  201902     300
8   Cliente2  201903     320
9   Cliente2  201904     370
10  Cliente2  201905     250
11  Cliente2  201906    1200
12  Cliente3  201901     200
13  Cliente3  201902     100
14  Cliente3  201903     150
15  Cliente3  201904       0
16  Cliente3  201905     300
17  Cliente3  201906     300
18  Cliente4  201901     330
19  Cliente4  201902     290
20  Cliente4  201903     150
21  Cliente4  201904     180
22  Cliente4  201905     270
23  Cliente4  201906     350

In [6]:
def calcular_suma(dic):

    # Estos son los valores iniciales que se irán modificando conforme avance el bucle.
    cliente_inicial = 'Cliente1'
    ahorro = 0
    logrado = 0

    res_cliente = []
    res_fecha = []
    res_ahorro = []

    for clave, valores in dic.items():
        filas = len(valores)
        # Aquí se obtiene el número de filas para iterar a continuación.

    for i in range(filas):
        if (cliente_inicial == dic['cliente'][i]) and (logrado == 0):       # Si el cliente de la iteración es el mismo que tenemos almacenado
            ahorro += dic['ahorro'][i]                                      # significa que podemos seguir sumando el ahorro.
            # print(ahorro, ahorros_pd['cliente'][i])
            if ahorro > 1000:                                               # Cuando el ahorro supera los 1000 €, guardamos los valores de cliente,
                print(dic['cliente'][i], dic['fecha'][i], ahorro)           # fecha y ahorro hasta ese momento.
                res_cliente.append(dic['cliente'][i])
                res_fecha.append(dic['fecha'][i])
                res_ahorro.append(ahorro)
                logrado = 1                                                 # Con la variable 'logrado' se evita que si el cliente es el mismo en la 
                # print(logrado)                                            # próxima iteración, no entremos al if inicial.

        elif cliente_inicial != dic['cliente'][i]:                          # Si el cliente de la iteración es diferente al almacenado, resetamos 
            cliente_inicial = dic['cliente'][i]                             # los valores de cliente inicial y logrado, para que en una próxima iteración
            logrado = 0                                                     # sea posible volver a entrar al if inicial. También se comienza el nuevo 
            ahorro = 0                                                      # cómputo de ahorro.
            ahorro += dic['ahorro'][i]
    return (res_cliente, res_fecha, res_ahorro)

calcular_suma(ahorros_pd)

Cliente2 201904 1240
Cliente3 201906 1050
Cliente4 201905 1220

(['Cliente2', 'Cliente3', 'Cliente4'],
 [201904, 201906, 201905],
 [1240, 1050, 1220])